Fixed requirements (wouldn't build on docker otherwise)
ruqqus/ruqqus pull request #773
Opened 2021-06-19 16:57 UTC by devBoi76

When I tried to launch ruqqus in docker it said it needed psutil>=5.7.0 so I added it

2021-06-19 19:06 UTC, devBoi76 commented
Update: I fixed it so it returns the right path for the css file

2021-06-20 15:39 UTC, Panjkrc requested changes

2021-06-20 15:39 UTC, Panjkrc commented on ruqqus/routes/static.py
> +		return make_response(send_file(f'../ruqqus/assets/style/{file}.css'))
This change did not work when testing in a production enviroment
You should fix that. The following worked:
```python
return make_response(send_file(f'./assets/style/{file}.css'))
```

2021-06-20 15:39 UTC, Panjkrc commented on README.md
> +*Note - you may need to add `- CLOUDFLARE_ZONE=false` to `environment` in `docker-compose.yml` if its not already there*
Kind of pointless since you also updated `docker-compose.yml`

2021-06-22 11:24 UTC, merged